"""
Build backend/data/kanji/*.json from embedded curriculum lists.

Run from repo root:
  python backend/scripts/build_character_seeds.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data" / "kanji"

# JLPT N5 kanji (common study set). Readings are learner-friendly, not exhaustive.
N5_ROWS: list[dict[str, object]] = [
    {"character": "一", "meanings": "one", "on_readings": "イチ", "kun_readings": "ひと", "stroke_count": 1, "jlpt_level": "N5"},
    {"character": "二", "meanings": "two", "on_readings": "ニ", "kun_readings": "ふた", "stroke_count": 2, "jlpt_level": "N5"},
    {"character": "三", "meanings": "three", "on_readings": "サン", "kun_readings": "み", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "四", "meanings": "four", "on_readings": "シ", "kun_readings": "よん", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "五", "meanings": "five", "on_readings": "ゴ", "kun_readings": "いつ", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "六", "meanings": "six", "on_readings": "ロク", "kun_readings": "む", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "七", "meanings": "seven", "on_readings": "シチ", "kun_readings": "なな", "stroke_count": 2, "jlpt_level": "N5"},
    {"character": "八", "meanings": "eight", "on_readings": "ハチ", "kun_readings": "や", "stroke_count": 2, "jlpt_level": "N5"},
    {"character": "九", "meanings": "nine", "on_readings": "キュウ", "kun_readings": "ここの", "stroke_count": 2, "jlpt_level": "N5"},
    {"character": "十", "meanings": "ten", "on_readings": "ジュウ", "kun_readings": "とお", "stroke_count": 2, "jlpt_level": "N5"},
    {"character": "百", "meanings": "hundred", "on_readings": "ヒャク", "kun_readings": "もも", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "千", "meanings": "thousand", "on_readings": "セン", "kun_readings": "ち", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "万", "meanings": "ten thousand", "on_readings": "マン", "kun_readings": None, "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "円", "meanings": "yen, circle", "on_readings": "エン", "kun_readings": "まる", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "人", "meanings": "person", "on_readings": "ジン、ニン", "kun_readings": "ひと", "stroke_count": 2, "jlpt_level": "N5"},
    {"character": "男", "meanings": "man, male", "on_readings": "ダン、ナン", "kun_readings": "おとこ", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "女", "meanings": "woman, female", "on_readings": "ジョ", "kun_readings": "おんな", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "子", "meanings": "child", "on_readings": "シ", "kun_readings": "こ", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "母", "meanings": "mother", "on_readings": "ボ", "kun_readings": "はは", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "父", "meanings": "father", "on_readings": "フ", "kun_readings": "ちち", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "友", "meanings": "friend", "on_readings": "ユウ", "kun_readings": "とも", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "先", "meanings": "before, previous", "on_readings": "セン", "kun_readings": "さき", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "生", "meanings": "life, birth", "on_readings": "セイ、ショウ", "kun_readings": "い", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "学", "meanings": "study, learning", "on_readings": "ガク", "kun_readings": "まな", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "校", "meanings": "school", "on_readings": "コウ", "kun_readings": None, "stroke_count": 10, "jlpt_level": "N5"},
    {"character": "名", "meanings": "name", "on_readings": "メイ、ミョウ", "kun_readings": "な", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "年", "meanings": "year", "on_readings": "ネン", "kun_readings": "とし", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "月", "meanings": "month, moon", "on_readings": "ゲツ、ガツ", "kun_readings": "つき", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "日", "meanings": "day, sun", "on_readings": "ニチ、ジツ", "kun_readings": "ひ", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "時", "meanings": "time, hour", "on_readings": "ジ", "kun_readings": "とき", "stroke_count": 10, "jlpt_level": "N5"},
    {"character": "分", "meanings": "minute, part", "on_readings": "ブン、フン", "kun_readings": "わ", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "半", "meanings": "half", "on_readings": "ハン", "kun_readings": "なか", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "今", "meanings": "now", "on_readings": "コン、キン", "kun_readings": "いま", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "明", "meanings": "bright, tomorrow", "on_readings": "メイ、ミョウ", "kun_readings": "あ", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "昨", "meanings": "previous (yesterday)", "on_readings": "サク", "kun_readings": None, "stroke_count": 9, "jlpt_level": "N5"},
    {"character": "毎", "meanings": "every", "on_readings": "マイ", "kun_readings": "ごと", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "何", "meanings": "what", "on_readings": "カ", "kun_readings": "なに", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "午", "meanings": "noon", "on_readings": "ゴ", "kun_readings": None, "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "前", "meanings": "before, front", "on_readings": "ゼン", "kun_readings": "まえ", "stroke_count": 9, "jlpt_level": "N5"},
    {"character": "後", "meanings": "after, behind", "on_readings": "ゴ、コウ", "kun_readings": "あと", "stroke_count": 9, "jlpt_level": "N5"},
    {"character": "上", "meanings": "up, above", "on_readings": "ジョウ", "kun_readings": "うえ", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "下", "meanings": "down, below", "on_readings": "カ、ゲ", "kun_readings": "した", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "左", "meanings": "left", "on_readings": "サ", "kun_readings": "ひだり", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "右", "meanings": "right", "on_readings": "ウ、ユウ", "kun_readings": "みぎ", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "中", "meanings": "middle, inside", "on_readings": "チュウ", "kun_readings": "なか", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "外", "meanings": "outside", "on_readings": "ガイ、ゲ", "kun_readings": "そと", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "内", "meanings": "inside", "on_readings": "ナイ、ダイ", "kun_readings": "うち", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "大", "meanings": "big", "on_readings": "ダイ、タイ", "kun_readings": "おお", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "小", "meanings": "small", "on_readings": "ショウ", "kun_readings": "ちい", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "多", "meanings": "many", "on_readings": "タ", "kun_readings": "おお", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "少", "meanings": "few", "on_readings": "ショウ", "kun_readings": "すく", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "長", "meanings": "long, leader", "on_readings": "チョウ", "kun_readings": "なが", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "高", "meanings": "high, expensive", "on_readings": "コウ", "kun_readings": "たか", "stroke_count": 10, "jlpt_level": "N5"},
    {"character": "新", "meanings": "new", "on_readings": "シン", "kun_readings": "あたら", "stroke_count": 13, "jlpt_level": "N5"},
    {"character": "古", "meanings": "old", "on_readings": "コ", "kun_readings": "ふる", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "白", "meanings": "white", "on_readings": "ハク、ビャク", "kun_readings": "しろ", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "赤", "meanings": "red", "on_readings": "セキ、シャク", "kun_readings": "あか", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "青", "meanings": "blue, green", "on_readings": "セイ、ショウ", "kun_readings": "あお", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "色", "meanings": "color", "on_readings": "ショク", "kun_readings": "いろ", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "東", "meanings": "east", "on_readings": "トウ", "kun_readings": "ひがし", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "西", "meanings": "west", "on_readings": "セイ、サイ", "kun_readings": "にし", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "南", "meanings": "south", "on_readings": "ナン", "kun_readings": "みなみ", "stroke_count": 9, "jlpt_level": "N5"},
    {"character": "北", "meanings": "north", "on_readings": "ホク", "kun_readings": "きた", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "国", "meanings": "country", "on_readings": "コク", "kun_readings": "くに", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "語", "meanings": "language, word", "on_readings": "ゴ", "kun_readings": "かた", "stroke_count": 14, "jlpt_level": "N5"},
    {"character": "本", "meanings": "book, origin", "on_readings": "ホン", "kun_readings": "もと", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "書", "meanings": "write", "on_readings": "ショ", "kun_readings": "か", "stroke_count": 10, "jlpt_level": "N5"},
    {"character": "読", "meanings": "read", "on_readings": "ドク、トク", "kun_readings": "よ", "stroke_count": 14, "jlpt_level": "N5"},
    {"character": "聞", "meanings": "hear, ask", "on_readings": "ブン、モン", "kun_readings": "き", "stroke_count": 14, "jlpt_level": "N5"},
    {"character": "話", "meanings": "talk, story", "on_readings": "ワ", "kun_readings": "はな", "stroke_count": 13, "jlpt_level": "N5"},
    {"character": "言", "meanings": "say, word", "on_readings": "ゲン、ゴン", "kun_readings": "い", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "食", "meanings": "eat, food", "on_readings": "ショク、ジキ", "kun_readings": "た", "stroke_count": 9, "jlpt_level": "N5"},
    {"character": "飲", "meanings": "drink", "on_readings": "イン", "kun_readings": "の", "stroke_count": 12, "jlpt_level": "N5"},
    {"character": "見", "meanings": "see", "on_readings": "ケン", "kun_readings": "み", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "行", "meanings": "go, act", "on_readings": "コウ、ギョウ", "kun_readings": "い", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "来", "meanings": "come", "on_readings": "ライ", "kun_readings": "く", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "帰", "meanings": "return home", "on_readings": "キ", "kun_readings": "かえ", "stroke_count": 10, "jlpt_level": "N5"},
    {"character": "入", "meanings": "enter", "on_readings": "ニュウ", "kun_readings": "はい", "stroke_count": 2, "jlpt_level": "N5"},
    {"character": "出", "meanings": "exit, leave", "on_readings": "シュツ、スイ", "kun_readings": "で", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "立", "meanings": "stand", "on_readings": "リツ", "kun_readings": "た", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "休", "meanings": "rest", "on_readings": "キュウ", "kun_readings": "やす", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "買", "meanings": "buy", "on_readings": "バイ", "kun_readings": "か", "stroke_count": 12, "jlpt_level": "N5"},
    {"character": "売", "meanings": "sell", "on_readings": "バイ", "kun_readings": "う", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "会", "meanings": "meet, society", "on_readings": "カイ、エ", "kun_readings": "あ", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "社", "meanings": "company, shrine", "on_readings": "シャ", "kun_readings": "やしろ", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "店", "meanings": "shop", "on_readings": "テン", "kun_readings": "みせ", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "駅", "meanings": "station", "on_readings": "エキ", "kun_readings": None, "stroke_count": 14, "jlpt_level": "N5"},
    {"character": "道", "meanings": "road, way", "on_readings": "ドウ、トウ", "kun_readings": "みち", "stroke_count": 12, "jlpt_level": "N5"},
    {"character": "車", "meanings": "car, vehicle", "on_readings": "シャ", "kun_readings": "くるま", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "電", "meanings": "electricity", "on_readings": "デン", "kun_readings": None, "stroke_count": 13, "jlpt_level": "N5"},
    {"character": "自", "meanings": "self", "on_readings": "ジ、シ", "kun_readings": "みずか", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "室", "meanings": "room", "on_readings": "シツ", "kun_readings": "むろ", "stroke_count": 9, "jlpt_level": "N5"},
    {"character": "家", "meanings": "house, family", "on_readings": "カ、ケ", "kun_readings": "いえ", "stroke_count": 10, "jlpt_level": "N5"},
    {"character": "門", "meanings": "gate", "on_readings": "モン", "kun_readings": "かど", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "口", "meanings": "mouth", "on_readings": "コウ、ク", "kun_readings": "くち", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "手", "meanings": "hand", "on_readings": "シュ", "kun_readings": "て", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "足", "meanings": "foot, leg", "on_readings": "ソク", "kun_readings": "あし", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "目", "meanings": "eye", "on_readings": "モク、ボク", "kun_readings": "め", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "耳", "meanings": "ear", "on_readings": "ジ", "kun_readings": "みみ", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "体", "meanings": "body", "on_readings": "タイ、テイ", "kun_readings": "からだ", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "力", "meanings": "power", "on_readings": "リョク、リキ", "kun_readings": "ちから", "stroke_count": 2, "jlpt_level": "N5"},
    {"character": "天", "meanings": "heaven, sky", "on_readings": "テン", "kun_readings": "あま", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "気", "meanings": "spirit, air", "on_readings": "キ、ケ", "kun_readings": "き", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "雨", "meanings": "rain", "on_readings": "ウ", "kun_readings": "あめ", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "雪", "meanings": "snow", "on_readings": "セツ", "kun_readings": "ゆき", "stroke_count": 11, "jlpt_level": "N5"},
    {"character": "花", "meanings": "flower", "on_readings": "カ", "kun_readings": "はな", "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "火", "meanings": "fire", "on_readings": "カ", "kun_readings": "ひ", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "水", "meanings": "water", "on_readings": "スイ", "kun_readings": "みず", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "土", "meanings": "earth, soil", "on_readings": "ド、ト", "kun_readings": "つち", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "木", "meanings": "tree, wood", "on_readings": "ボク、モク", "kun_readings": "き", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "金", "meanings": "gold, money", "on_readings": "キン、コン", "kun_readings": "かね", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "山", "meanings": "mountain", "on_readings": "サン", "kun_readings": "やま", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "川", "meanings": "river", "on_readings": "セン", "kun_readings": "かわ", "stroke_count": 3, "jlpt_level": "N5"},
    {"character": "海", "meanings": "sea", "on_readings": "カイ", "kun_readings": "うみ", "stroke_count": 9, "jlpt_level": "N5"},
    {"character": "空", "meanings": "sky, empty", "on_readings": "クウ", "kun_readings": "そら", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "林", "meanings": "grove", "on_readings": "リン", "kun_readings": "はやし", "stroke_count": 8, "jlpt_level": "N5"},
    {"character": "田", "meanings": "rice field", "on_readings": "デン", "kun_readings": "た", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "犬", "meanings": "dog", "on_readings": "ケン", "kun_readings": "いぬ", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "猫", "meanings": "cat", "on_readings": "ビョウ", "kun_readings": "ねこ", "stroke_count": 11, "jlpt_level": "N5"},
    {"character": "魚", "meanings": "fish", "on_readings": "ギョ", "kun_readings": "さかな", "stroke_count": 11, "jlpt_level": "N5"},
    {"character": "鳥", "meanings": "bird", "on_readings": "チョウ", "kun_readings": "とり", "stroke_count": 11, "jlpt_level": "N5"},
    {"character": "虫", "meanings": "insect", "on_readings": "チュウ", "kun_readings": "むし", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "間", "meanings": "interval, between", "on_readings": "カン、ケン", "kun_readings": "あいだ", "stroke_count": 12, "jlpt_level": "N5"},
    {"character": "方", "meanings": "direction, way", "on_readings": "ホウ", "kun_readings": "かた", "stroke_count": 4, "jlpt_level": "N5"},
    {"character": "正", "meanings": "correct", "on_readings": "セイ、ショウ", "kun_readings": "ただ", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "安", "meanings": "cheap, peaceful", "on_readings": "アン", "kun_readings": "やす", "stroke_count": 6, "jlpt_level": "N5"},
    {"character": "医", "meanings": "medicine, doctor", "on_readings": "イ", "kun_readings": None, "stroke_count": 7, "jlpt_level": "N5"},
    {"character": "院", "meanings": "institution", "on_readings": "イン", "kun_readings": None, "stroke_count": 10, "jlpt_level": "N5"},
    {"character": "去", "meanings": "past, leave", "on_readings": "キョ、コ", "kun_readings": "さ", "stroke_count": 5, "jlpt_level": "N5"},
    {"character": "週", "meanings": "week", "on_readings": "シュウ", "kun_readings": None, "stroke_count": 11, "jlpt_level": "N5"},
    {"character": "曜", "meanings": "weekday", "on_readings": "ヨウ", "kun_readings": None, "stroke_count": 18, "jlpt_level": "N5"},
]

# HSK 1 vocabulary as single-character entries where possible; multi-char as notes on first char.
HSK1_ROWS: list[dict[str, object]] = [
    {"character": "爱", "meanings": "love", "on_readings": "ài", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "八", "meanings": "eight", "on_readings": "bā", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "爸", "meanings": "dad (colloquial)", "on_readings": "bà", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1 — 爸爸"},
    {"character": "白", "meanings": "white", "on_readings": "bái", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "百", "meanings": "hundred", "on_readings": "bǎi", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "本", "meanings": "book, measure word", "on_readings": "běn", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "不", "meanings": "not", "on_readings": "bù", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "菜", "meanings": "dish, vegetable", "on_readings": "cài", "kun_readings": None, "stroke_count": 11, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "茶", "meanings": "tea", "on_readings": "chá", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "吃", "meanings": "eat", "on_readings": "chī", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "出", "meanings": "go out", "on_readings": "chū", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "打", "meanings": "hit, do (phone)", "on_readings": "dǎ", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "大", "meanings": "big", "on_readings": "dà", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "的", "meanings": "possessive particle", "on_readings": "de", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "点", "meanings": "o'clock, point", "on_readings": "diǎn", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "电", "meanings": "electric", "on_readings": "diàn", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1 — 电脑"},
    {"character": "东", "meanings": "east", "on_readings": "dōng", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "都", "meanings": "all, both", "on_readings": "dōu", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "读", "meanings": "read", "on_readings": "dú", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "对", "meanings": "correct, toward", "on_readings": "duì", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "多", "meanings": "many", "on_readings": "duō", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "儿", "meanings": "son, suffix", "on_readings": "ér", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1 — 儿子"},
    {"character": "二", "meanings": "two", "on_readings": "èr", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "饭", "meanings": "meal, rice", "on_readings": "fàn", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "飞", "meanings": "fly", "on_readings": "fēi", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "分", "meanings": "minute", "on_readings": "fēn", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "高", "meanings": "tall, high", "on_readings": "gāo", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "个", "meanings": "general measure word", "on_readings": "gè", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "工", "meanings": "work", "on_readings": "gōng", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1 — 工作"},
    {"character": "狗", "meanings": "dog", "on_readings": "gǒu", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "汉", "meanings": "Han Chinese", "on_readings": "hàn", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1 — 汉语"},
    {"character": "好", "meanings": "good", "on_readings": "hǎo", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "号", "meanings": "number, day", "on_readings": "hào", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "喝", "meanings": "drink", "on_readings": "hē", "kun_readings": None, "stroke_count": 12, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "和", "meanings": "and, with", "on_readings": "hé", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "很", "meanings": "very", "on_readings": "hěn", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "后", "meanings": "behind, after", "on_readings": "hòu", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "回", "meanings": "return", "on_readings": "huí", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "会", "meanings": "can, meeting", "on_readings": "huì", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "几", "meanings": "how many", "on_readings": "jǐ", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "家", "meanings": "home, family", "on_readings": "jiā", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "叫", "meanings": "call, be called", "on_readings": "jiào", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "今", "meanings": "now", "on_readings": "jīn", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1 — 今天"},
    {"character": "九", "meanings": "nine", "on_readings": "jiǔ", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "开", "meanings": "open, drive", "on_readings": "kāi", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "看", "meanings": "look, read", "on_readings": "kàn", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "块", "meanings": "piece, yuan (colloq.)", "on_readings": "kuài", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "来", "meanings": "come", "on_readings": "lái", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "老", "meanings": "old", "on_readings": "lǎo", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1 — 老师"},
    {"character": "了", "meanings": "aspect particle", "on_readings": "le", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "冷", "meanings": "cold", "on_readings": "lěng", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "里", "meanings": "inside", "on_readings": "lǐ", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "六", "meanings": "six", "on_readings": "liù", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "妈", "meanings": "mom", "on_readings": "mā", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1 — 妈妈"},
    {"character": "吗", "meanings": "question particle", "on_readings": "ma", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "买", "meanings": "buy", "on_readings": "mǎi", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "猫", "meanings": "cat", "on_readings": "māo", "kun_readings": None, "stroke_count": 11, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "没", "meanings": "not have", "on_readings": "méi", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "米", "meanings": "rice", "on_readings": "mǐ", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1 — 米饭"},
    {"character": "名", "meanings": "name", "on_readings": "míng", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "明", "meanings": "bright, tomorrow", "on_readings": "míng", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1 — 明天"},
    {"character": "哪", "meanings": "which", "on_readings": "nǎ", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "那", "meanings": "that", "on_readings": "nà", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "呢", "meanings": "question particle", "on_readings": "ne", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "能", "meanings": "can", "on_readings": "néng", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "你", "meanings": "you", "on_readings": "nǐ", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "年", "meanings": "year", "on_readings": "nián", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "女", "meanings": "female", "on_readings": "nǚ", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1 — 女儿"},
    {"character": "朋", "meanings": "friend", "on_readings": "péng", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1 — 朋友"},
    {"character": "漂", "meanings": "pretty", "on_readings": "piào", "kun_readings": None, "stroke_count": 14, "jlpt_level": None, "notes": "HSK 1 — 漂亮"},
    {"character": "苹", "meanings": "apple", "on_readings": "píng", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1 — 苹果"},
    {"character": "七", "meanings": "seven", "on_readings": "qī", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "前", "meanings": "front, before", "on_readings": "qián", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "钱", "meanings": "money", "on_readings": "qián", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "请", "meanings": "please", "on_readings": "qǐng", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "去", "meanings": "go", "on_readings": "qù", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "热", "meanings": "hot", "on_readings": "rè", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "人", "meanings": "person", "on_readings": "rén", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "认", "meanings": "recognize", "on_readings": "rèn", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1 — 认识"},
    {"character": "日", "meanings": "day, sun", "on_readings": "rì", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "三", "meanings": "three", "on_readings": "sān", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "商", "meanings": "commerce", "on_readings": "shāng", "kun_readings": None, "stroke_count": 11, "jlpt_level": None, "notes": "HSK 1 — 商店"},
    {"character": "上", "meanings": "up, on", "on_readings": "shàng", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "少", "meanings": "few", "on_readings": "shǎo", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "谁", "meanings": "who", "on_readings": "shéi", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "什", "meanings": "what", "on_readings": "shén", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1 — 什么"},
    {"character": "十", "meanings": "ten", "on_readings": "shí", "kun_readings": None, "stroke_count": 2, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "时", "meanings": "time", "on_readings": "shí", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1 — 时候"},
    {"character": "是", "meanings": "to be", "on_readings": "shì", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "书", "meanings": "book", "on_readings": "shū", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "水", "meanings": "water", "on_readings": "shuǐ", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "睡", "meanings": "sleep", "on_readings": "shuì", "kun_readings": None, "stroke_count": 13, "jlpt_level": None, "notes": "HSK 1 — 睡觉"},
    {"character": "说", "meanings": "speak", "on_readings": "shuō", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "四", "meanings": "four", "on_readings": "sì", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "岁", "meanings": "years (age)", "on_readings": "suì", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "他", "meanings": "he", "on_readings": "tā", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "她", "meanings": "she", "on_readings": "tā", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "太", "meanings": "too, very", "on_readings": "tài", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "天", "meanings": "sky, day", "on_readings": "tiān", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1 — 天气"},
    {"character": "听", "meanings": "listen", "on_readings": "tīng", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "同", "meanings": "same", "on_readings": "tóng", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1 — 同学"},
    {"character": "我", "meanings": "I, me", "on_readings": "wǒ", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "五", "meanings": "five", "on_readings": "wǔ", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "喜", "meanings": "like, happy", "on_readings": "xǐ", "kun_readings": None, "stroke_count": 12, "jlpt_level": None, "notes": "HSK 1 — 喜欢"},
    {"character": "下", "meanings": "down", "on_readings": "xià", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "雨", "meanings": "rain", "on_readings": "yǔ", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1 — 下雨"},
    {"character": "先", "meanings": "first", "on_readings": "xiān", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1 — 先生"},
    {"character": "现", "meanings": "now", "on_readings": "xiàn", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1 — 现在"},
    {"character": "想", "meanings": "think, miss", "on_readings": "xiǎng", "kun_readings": None, "stroke_count": 13, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "小", "meanings": "small", "on_readings": "xiǎo", "kun_readings": None, "stroke_count": 3, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "些", "meanings": "some", "on_readings": "xiē", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "写", "meanings": "write", "on_readings": "xiě", "kun_readings": None, "stroke_count": 5, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "谢", "meanings": "thank", "on_readings": "xiè", "kun_readings": None, "stroke_count": 12, "jlpt_level": None, "notes": "HSK 1 — 谢谢"},
    {"character": "星", "meanings": "star", "on_readings": "xīng", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1 — 星期"},
    {"character": "学", "meanings": "study", "on_readings": "xué", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "一", "meanings": "one", "on_readings": "yī", "kun_readings": None, "stroke_count": 1, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "衣", "meanings": "clothes", "on_readings": "yī", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1 — 衣服"},
    {"character": "医", "meanings": "medicine", "on_readings": "yī", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1 — 医生/医院"},
    {"character": "椅", "meanings": "chair", "on_readings": "yǐ", "kun_readings": None, "stroke_count": 12, "jlpt_level": None, "notes": "HSK 1 — 椅子"},
    {"character": "有", "meanings": "have", "on_readings": "yǒu", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "月", "meanings": "month, moon", "on_readings": "yuè", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "再", "meanings": "again", "on_readings": "zài", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "在", "meanings": "at, in", "on_readings": "zài", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "怎", "meanings": "how", "on_readings": "zěn", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1 — 怎么"},
    {"character": "这", "meanings": "this", "on_readings": "zhè", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "中", "meanings": "middle, China", "on_readings": "zhōng", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1 — 中国"},
    {"character": "住", "meanings": "live", "on_readings": "zhù", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "桌", "meanings": "table", "on_readings": "zhuō", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1 — 桌子"},
    {"character": "字", "meanings": "character", "on_readings": "zì", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "昨", "meanings": "yesterday", "on_readings": "zuó", "kun_readings": None, "stroke_count": 9, "jlpt_level": None, "notes": "HSK 1 — 昨天"},
    {"character": "做", "meanings": "do, make", "on_readings": "zuò", "kun_readings": None, "stroke_count": 11, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "坐", "meanings": "sit", "on_readings": "zuò", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "车", "meanings": "vehicle", "on_readings": "chē", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1 — 出租车"},
    {"character": "机", "meanings": "machine", "on_readings": "jī", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1 — 飞机"},
    {"character": "影", "meanings": "shadow, film", "on_readings": "yǐng", "kun_readings": None, "stroke_count": 15, "jlpt_level": None, "notes": "HSK 1 — 电影"},
    {"character": "西", "meanings": "west", "on_readings": "xī", "kun_readings": None, "stroke_count": 6, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "果", "meanings": "fruit", "on_readings": "guǒ", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1 — 水果"},
    {"character": "起", "meanings": "rise", "on_readings": "qǐ", "kun_readings": None, "stroke_count": 10, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "床", "meanings": "bed", "on_readings": "chuáng", "kun_readings": None, "stroke_count": 7, "jlpt_level": None, "notes": "HSK 1"},
    {"character": "气", "meanings": "air, weather", "on_readings": "qì", "kun_readings": None, "stroke_count": 4, "jlpt_level": None, "notes": "HSK 1 — 天气"},
    {"character": "话", "meanings": "speech", "on_readings": "huà", "kun_readings": None, "stroke_count": 13, "jlpt_level": None, "notes": "HSK 1 — 电话"},
    {"character": "视", "meanings": "view", "on_readings": "shì", "kun_readings": None, "stroke_count": 8, "jlpt_level": None, "notes": "HSK 1 — 电视"},
]

def _dedupe(rows: list[dict[str, object]]) -> list[dict[str, object]]:
    seen: set[str] = set()
    out: list[dict[str, object]] = []
    for row in rows:
        ch = str(row["character"])
        if ch in seen:
            continue
        seen.add(ch)
        out.append(row)
    return out


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ja = _dedupe(N5_ROWS)
    zh = _dedupe(HSK1_ROWS)
    (OUT_DIR / "ja.json").write_text(
        json.dumps(ja, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (OUT_DIR / "zh.json").write_text(
        json.dumps(zh, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(ja)} Japanese and {len(zh)} Chinese entries to {OUT_DIR}")


if __name__ == "__main__":
    main()
