"""JLPT N4 and HSK 2 rows merged by build_character_seeds.py."""

N4_ROWS: list[dict[str, object]] = [
    {"character": "力", "meanings": "power", "on_readings": "リョク", "kun_readings": "ちから", "stroke_count": 2, "jlpt_level": "N4"},
    {"character": "町", "meanings": "town", "on_readings": "チョウ", "kun_readings": "まち", "stroke_count": 7, "jlpt_level": "N4"},
    {"character": "料", "meanings": "fee, materials", "on_readings": "リョウ", "kun_readings": None, "stroke_count": 10, "jlpt_level": "N4"},
    {"character": "理", "meanings": "reason, manage", "on_readings": "リ", "kun_readings": None, "stroke_count": 11, "jlpt_level": "N4"},
    {"character": "解", "meanings": "unravel, answer", "on_readings": "カイ", "kun_readings": "と", "stroke_count": 13, "jlpt_level": "N4"},
    {"character": "急", "meanings": "urgent", "on_readings": "キュウ", "kun_readings": "いそ", "stroke_count": 9, "jlpt_level": "N4"},
    {"character": "持", "meanings": "hold", "on_readings": "ジ", "kun_readings": "も", "stroke_count": 9, "jlpt_level": "N4"},
    {"character": "待", "meanings": "wait", "on_readings": "タイ", "kun_readings": "ま", "stroke_count": 9, "jlpt_level": "N4"},
    {"character": "思", "meanings": "think", "on_readings": "シ", "kun_readings": "おも", "stroke_count": 9, "jlpt_level": "N4"},
    {"character": "考", "meanings": "consider", "on_readings": "コウ", "kun_readings": "かんが", "stroke_count": 6, "jlpt_level": "N4"},
    {"character": "知", "meanings": "know", "on_readings": "チ", "kun_readings": "し", "stroke_count": 8, "jlpt_level": "N4"},
    {"character": "道", "meanings": "road, way", "on_readings": "ドウ", "kun_readings": "みち", "stroke_count": 12, "jlpt_level": "N4"},
    {"character": "運", "meanings": "carry, luck", "on_readings": "ウン", "kun_readings": "はこ", "stroke_count": 12, "jlpt_level": "N4"},
    {"character": "動", "meanings": "move", "on_readings": "ドウ", "kun_readings": "うご", "stroke_count": 11, "jlpt_level": "N4"},
    {"character": "働", "meanings": "work", "on_readings": "ドウ", "kun_readings": "はたら", "stroke_count": 13, "jlpt_level": "N4"},
    {"character": "始", "meanings": "begin", "on_readings": "シ", "kun_readings": "はじ", "stroke_count": 8, "jlpt_level": "N4"},
    {"character": "終", "meanings": "end", "on_readings": "シュウ", "kun_readings": "お", "stroke_count": 11, "jlpt_level": "N4"},
    {"character": "起", "meanings": "wake, rise", "on_readings": "キ", "kun_readings": "お", "stroke_count": 10, "jlpt_level": "N4"},
    {"character": "寝", "meanings": "sleep", "on_readings": "シン", "kun_readings": "ね", "stroke_count": 13, "jlpt_level": "N4"},
    {"character": "送", "meanings": "send", "on_readings": "ソウ", "kun_readings": "おく", "stroke_count": 9, "jlpt_level": "N4"},
    {"character": "届", "meanings": "deliver", "on_readings": "カイ", "kun_readings": "とど", "stroke_count": 8, "jlpt_level": "N4"},
    {"character": "注", "meanings": "pour, note", "on_readings": "チュウ", "kun_readings": "そそ", "stroke_count": 8, "jlpt_level": "N4"},
    {"character": "意", "meanings": "idea, mind", "on_readings": "イ", "kun_readings": None, "stroke_count": 13, "jlpt_level": "N4"},
    {"character": "味", "meanings": "taste", "on_readings": "ミ", "kun_readings": "あじ", "stroke_count": 8, "jlpt_level": "N4"},
    {"character": "便", "meanings": "convenience", "on_readings": "ベン", "kun_readings": "たよ", "stroke_count": 9, "jlpt_level": "N4"},
    {"character": "利", "meanings": "profit, sharp", "on_readings": "リ", "kun_readings": None, "stroke_count": 7, "jlpt_level": "N4"},
]

HSK2_ROWS: list[dict[str, object]] = [
    {"character": "旅", "meanings": "travel", "on_readings": "lǚ", "stroke_count": 10, "hsk_level": 2},
    {"character": "游", "meanings": "swim, travel", "on_readings": "yóu", "stroke_count": 12, "hsk_level": 2},
    {"character": "泳", "meanings": "swim", "on_readings": "yǒng", "stroke_count": 8, "hsk_level": 2},
    {"character": "跑", "meanings": "run", "on_readings": "pǎo", "stroke_count": 12, "hsk_level": 2},
    {"character": "步", "meanings": "step, walk", "on_readings": "bù", "stroke_count": 7, "hsk_level": 2},
    {"character": "题", "meanings": "topic, question", "on_readings": "tí", "stroke_count": 15, "hsk_level": 2},
    {"character": "问", "meanings": "ask", "on_readings": "wèn", "stroke_count": 6, "hsk_level": 2},
    {"character": "课", "meanings": "lesson", "on_readings": "kè", "stroke_count": 10, "hsk_level": 2},
    {"character": "室", "meanings": "room", "on_readings": "shì", "stroke_count": 9, "hsk_level": 2},
    {"character": "办", "meanings": "handle, office", "on_readings": "bàn", "stroke_count": 4, "hsk_level": 2},
    {"character": "公", "meanings": "public", "on_readings": "gōng", "stroke_count": 4, "hsk_level": 2},
    {"character": "司", "meanings": "manage", "on_readings": "sī", "stroke_count": 5, "hsk_level": 2},
    {"character": "机", "meanings": "machine; desk", "on_readings": "jī", "stroke_count": 6, "hsk_level": 2},
    {"character": "票", "meanings": "ticket", "on_readings": "piào", "stroke_count": 11, "hsk_level": 2},
    {"character": "场", "meanings": "field, place", "on_readings": "chǎng", "stroke_count": 6, "hsk_level": 2},
    {"character": "馆", "meanings": "building, hall", "on_readings": "guǎn", "stroke_count": 11, "hsk_level": 2},
    {"character": "图", "meanings": "map, picture", "on_readings": "tú", "stroke_count": 8, "hsk_level": 2},
    {"character": "纸", "meanings": "paper", "on_readings": "zhǐ", "stroke_count": 7, "hsk_level": 2},
    {"character": "笔", "meanings": "pen", "on_readings": "bǐ", "stroke_count": 10, "hsk_level": 2},
    {"character": "黑", "meanings": "black", "on_readings": "hēi", "stroke_count": 12, "hsk_level": 2},
    {"character": "红", "meanings": "red", "on_readings": "hóng", "stroke_count": 6, "hsk_level": 2},
    {"character": "绿", "meanings": "green", "on_readings": "lǜ", "stroke_count": 11, "hsk_level": 2},
    {"character": "黄", "meanings": "yellow", "on_readings": "huáng", "stroke_count": 12, "hsk_level": 2},
    {"character": "晴", "meanings": "clear (weather)", "on_readings": "qíng", "stroke_count": 12, "hsk_level": 2},
    {"character": "阴", "meanings": "cloudy", "on_readings": "yīn", "stroke_count": 6, "hsk_level": 2},
    {"character": "云", "meanings": "cloud", "on_readings": "yún", "stroke_count": 4, "hsk_level": 2},
    {"character": "风", "meanings": "wind", "on_readings": "fēng", "stroke_count": 4, "hsk_level": 2},
    {"character": "雪", "meanings": "snow", "on_readings": "xuě", "stroke_count": 11, "hsk_level": 2},
    {"character": "春", "meanings": "spring", "on_readings": "chūn", "stroke_count": 9, "hsk_level": 2},
    {"character": "夏", "meanings": "summer", "on_readings": "xià", "stroke_count": 10, "hsk_level": 2},
    {"character": "秋", "meanings": "autumn", "on_readings": "qiū", "stroke_count": 9, "hsk_level": 2},
    {"character": "冬", "meanings": "winter", "on_readings": "dōng", "stroke_count": 5, "hsk_level": 2},
    {"character": "姓", "meanings": "surname", "on_readings": "xìng", "stroke_count": 8, "hsk_level": 2},
    {"character": "岁", "meanings": "years of age", "on_readings": "suì", "stroke_count": 6, "hsk_level": 2},
    {"character": "零", "meanings": "zero", "on_readings": "líng", "stroke_count": 13, "hsk_level": 2},
    {"character": "百", "meanings": "hundred", "on_readings": "bǎi", "stroke_count": 6, "hsk_level": 2},
    {"character": "千", "meanings": "thousand", "on_readings": "qiān", "stroke_count": 3, "hsk_level": 2},
    {"character": "万", "meanings": "ten thousand", "on_readings": "wàn", "stroke_count": 3, "hsk_level": 2},
    {"character": "件", "meanings": "matter, item", "on_readings": "jiàn", "stroke_count": 6, "hsk_level": 2},
    {"character": "帮", "meanings": "help", "on_readings": "bāng", "stroke_count": 9, "hsk_level": 2},
    {"character": "助", "meanings": "assist", "on_readings": "zhù", "stroke_count": 7, "hsk_level": 2},
    {"character": "忙", "meanings": "busy", "on_readings": "máng", "stroke_count": 6, "hsk_level": 2},
    {"character": "累", "meanings": "tired", "on_readings": "lèi", "stroke_count": 11, "hsk_level": 2},
    {"character": "饿", "meanings": "hungry", "on_readings": "è", "stroke_count": 10, "hsk_level": 2},
    {"character": "渴", "meanings": "thirsty", "on_readings": "kě", "stroke_count": 12, "hsk_level": 2},
    {"character": "药", "meanings": "medicine", "on_readings": "yào", "stroke_count": 9, "hsk_level": 2},
    {"character": "疼", "meanings": "ache", "on_readings": "téng", "stroke_count": 10, "hsk_level": 2},
    {"character": "痛", "meanings": "pain", "on_readings": "tòng", "stroke_count": 12, "hsk_level": 2},
    {"character": "洗", "meanings": "wash", "on_readings": "xǐ", "stroke_count": 9, "hsk_level": 2},
    {"character": "澡", "meanings": "bath", "on_readings": "zǎo", "stroke_count": 16, "hsk_level": 2},
    {"character": "穿", "meanings": "wear", "on_readings": "chuān", "stroke_count": 9, "hsk_level": 2},
    {"character": "服", "meanings": "clothes", "on_readings": "fú", "stroke_count": 8, "hsk_level": 2},
    {"character": "鞋", "meanings": "shoes", "on_readings": "xié", "stroke_count": 15, "hsk_level": 2},
    {"character": "颜", "meanings": "face, color", "on_readings": "yán", "stroke_count": 15, "hsk_level": 2},
    {"character": "色", "meanings": "color", "on_readings": "sè", "stroke_count": 6, "hsk_level": 2},
]
